 // Declaração de Variaveis .
 // Variaveis séra onde os dados ira ficar armazenado .
 var nome;
 var cpf;
 var altura;
 var endereco;




 // Atribuição dos valores dentro das Variaveis 
 
 //no JavaScript Não precisamos colocar o tipo dos dados

  /* Quando o tipo do Valor a ser atribuido na Variavel for String 
   Colocamos aspas('') simples ou duplas ("") e no meio colomaos o valor */


   
 var nome =  'José Almeida da Silva ';
   
 var cpf = 12345678900;
 
 var altura = 1.78;
  
 var endereco = 'Rua A, 380 – Centro – Recife/PE ';

 
